name: Autograding Tests

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때 실행
  pull_request:
    branches:
      - main  # PR 생성 시 실행

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. divisors.py가 있는지 확인 (디버깅)
      - name: Check current directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Files in directory:"
          ls -la

      # 4. 테스트 실행 (Test 0)
      - name: test0
        id: test0
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: test0
          command: python divisors.py 100
          expected-output: "1 2 4 5 10 20 25 50 100"
          comparison-method: contains
          timeout: 10

      # 5. 테스트 실행 (Test 1)
      - name: test1
        id: test1
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: test1
          command: python divisors.py 23
          expected-output: "1 23"
          comparison-method: contains
          timeout: 10

      # 6. 결과 보고
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST0_RESULTS: "${{ steps.test0.outputs.result }}"
          TEST1_RESULTS: "${{ steps.test1.outputs.result }}"
        with:
          runners: test0,test1
